"""Add monto_pagado field to PrestamoIndividual

Revision ID: 452546f6a83e
Revises: 740502e6ea2e
Create Date: 2025-03-10 13:58:19.731470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452546f6a83e'
down_revision = '740502e6ea2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestamoindividual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_pagado', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestamoindividual', schema=None) as batch_op:
        batch_op.drop_column('monto_pagado')

    # ### end Alembic commands ###
