"""Añadir columna is_active al modelo Usuario

Revision ID: 6214a3d7f195
Revises: 2b3232b55ae9
Create Date: 2025-03-26 22:13:41.128408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6214a3d7f195'
down_revision = '2b3232b55ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
