"""Agregar tabla pago_parcial

Revision ID: 70c83bb69820
Revises: 968f3b9032df
Create Date: 2025-09-28 13:19:42.998719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c83bb69820'
down_revision = '968f3b9032df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pago_parcial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('monto_abono', sa.Float(), nullable=False),
    sa.Column('fecha_abono', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('usuario_registro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pago_id'], ['pago.id'], ),
    sa.ForeignKeyConstraint(['usuario_registro_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago_parcial')
    # ### end Alembic commands ###
