"""Permitir grupo_id como NULL en Cliente

Revision ID: 795a79b22d09
Revises: 6214a3d7f195
Create Date: 2025-04-03 23:02:12.353782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795a79b22d09'
down_revision = '6214a3d7f195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('grupo_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('grupo_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
