"""Actualización de modelos

Revision ID: 948906f62d77
Revises: 9e19fecd8348
Create Date: 2025-03-26 09:56:55.606768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948906f62d77'
down_revision = '9e19fecd8348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestamogrupal', schema=None) as batch_op:
        batch_op.drop_column('monto_total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestamogrupal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_total', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
