"""Agregando campos de fecha de cancelacion, dias de atraso y mora a Pagos

Revision ID: 968f3b9032df
Revises: eb635c92ea55
Create Date: 2025-09-19 10:40:44.766524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968f3b9032df'
down_revision = 'eb635c92ea55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('archivo')

    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_cancelacion_pago_cuota', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('dias_atraso', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monto_mora', sa.Float(), nullable=True))
        batch_op.alter_column('monto_pagado',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('monto_pendiente',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pago', schema=None) as batch_op:
        batch_op.alter_column('monto_pendiente',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('monto_pagado',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.drop_column('monto_mora')
        batch_op.drop_column('dias_atraso')
        batch_op.drop_column('fecha_cancelacion_pago_cuota')

    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo', sa.BLOB(), nullable=False))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DATETIME(), nullable=True))
        batch_op.alter_column('cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
