"""Cambio de fecha_desembolso a db.Date

Revision ID: 9e19fecd8348
Revises: e9c718bbfa2a
Create Date: 2025-03-23 21:04:38.346142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e19fecd8348'
down_revision = 'e9c718bbfa2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestamogrupal', schema=None) as batch_op:
        batch_op.alter_column('fecha_desembolso',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prestamogrupal', schema=None) as batch_op:
        batch_op.alter_column('fecha_desembolso',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
