"""Agregar geolocalizacion

Revision ID: e5412a639b93
Revises: 
Create Date: 2025-12-21 15:30:50.955928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5412a639b93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('referencia', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('latitud', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('longitud', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('longitud')
        batch_op.drop_column('latitud')
        batch_op.drop_column('referencia')
        batch_op.drop_column('direccion')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
